### ISSUE TITLE
jclock in dialog

### ISSUE THREAD

**Issue by tlpriest** [dsparling/jclock#1]
<div id="divphoneentry" class="divdialog centerpage ui-helper-hidden" title="Error">
<span id="jclock"></div>
</div>

$('#divphoneentry').dialog({
                autoOpen: false,
                modal: true,
            });

This dialog is opened and closed many times. stopClock(el) always has el of null, so the second call to $('#jclock').jclock() creates a second, third, etc. clock all updating the same element.

Each dialog open calls:

```
        var jclock_options = {
            utc: true,
            utc_offset: getoffset(data.Timezone)
        };
        $('#jclock').jclock(jclock_options);
```

switch(timezone) {
                case 'Alaskan Standard Time':
                retval = -9;
                break;
                case 'Atlantic Standard Time':
                retval = -4;
                break;
                case 'Central Standard Time':
                retval = -6;
                break;
                case 'Eastern Standard Time':
                retval = -5;
                break;
                case 'Hawaiian Standard Time':
                retval = -10;
                break;
                case 'Mountain Standard Time':
                retval = -7;
                break;
                case 'Newfoundland Standard Time':
                retval = -3.5;
                break;
                case 'Pacific Standard Time':
                retval = -8;
                break;
            }

So, if you open the dialog in Eastern and get 09:12:34 and then open the dialog again using the same code but on Mountain Time, you get a flashing clock between 09:12:34 and 07:12:34 because the stopClock(el) for the eastern time clock did not work. el.isrunning and el.timerid is always false on the second call, so the mountain clock does not stop the eastern clock.

firebug shows span#jclock is defined as el, but not el.isrunning

**Comment by dsparling** [comment]
Closing for now due age of issue, going to consider this a feature request, and stopClock is already on my todo list.
