### ISSUE TITLE
.Destroy() Clock

### ISSUE THREAD

**Issue by lozaria** [dsparling/jclock#5]
Hello,

In the previous version there was clock.destroy() function.
How can I stop the execution of a started clock in the current version?

I need that in order to start another clock in the same div but with different gmt.

Many thanks!

**Comment by andyg2** [comment]
Did you find a solution for this?

**Comment by dsparling** [comment]
HI Andy - I need to clean up tickets and make sure everything has been addressed. I've had a few pull requests, so I may have missed this one. I'll look at it over the weekend.

**Comment by andyg2** [comment]
Thanks, currently I'm using $("#jclockid").unbind().parent().empty().append('html for div id = jclock').jclock(); when I need to use the same div with a new clock.

**Comment by dsparling** [comment]
Yeah, you shouldn't have to do that. I took a look last night, and somewhere along the way the stopClock method quit working. I've finally got a little time to work on it. Thanks for persisting :)

**Comment by dsparling** [comment]
As far as clock.destroy(), I'm digging through old versions to see what changed...

**Comment by dsparling** [comment]
Andy, as you've got a solution for this, I'm going to close this particular issue with the caveat that I will revisit the stopClock functionality in the next release.

**Comment by andyg2** [comment]
OK, no worries.
